export const data = {
  id: {
    seo: {
      title: "Dava Dwi | IT Leader & Full Stack Developer",
      description:
        "Membangun sistem web dan mobile, meliputi Performance Review Sys, CRM, manajemen afiliasi, hingga sinkronisasi data e-commerce. Berpengalaman dengan PHP, Laravel, CodeIgniter, React, Node.js, dan integrasi API.",
      keywords:
        "Muhamad Dava, Dava Dwi, IT Leader, Full Stack Developer, Web Developer Bekasi, Software Engineer Indonesia, PHP, Laravel, CodeIgniter, JavaScript, React JS, Node JS, React Native, REST API, Sistem Performance Review Sys, CRM, Integrasi API, Webhook",
    },
    nav: {
      viewExp: "Lihat Pengalaman",
      viewProj: "Proyek Pilihan",
      featuredProj: "Proyek Pilihan",
      workExp: "Pengalaman Kerja",
      location: "Lokasi",
      experience: "Pengalaman",
      coreStacks: "Tech Stack Utama",
      otherSkills: "Tools & Keahlian Lain",
      softSkills: "Interpersonal",
      visitProject: "Buka Project",
      viewSource: "Lihat Source",
      screenshotOnly: "Screenshot Only",
      downloadCV: "Unduh CV (PDF)",
    },
    personal: {
      name: "Dava Dwi",
      fullName: "Muhamad Dava Dwi Saputra",
      role: "IT Leader | Full Stack Developer",
      email: "davadwi123@gmail.com",
      linkedin: "linkedin.com/in/muhamaddava",
      whatsapp: "6285183323882",
      github: "github.com/davadwis",
      city: "Kab. Bekasi, Indonesia",
      yearsExp: "2+ Tahun",
      headline:
        "Membangun sistem yang solid untuk bisnis yang terus berkembang.",
      summary:
        "Saya adalah seorang IT Leader & Full Stack Developer yang berfokus pada arsitektur backend, integrasi API, dan efisiensi operasional. Berpengalaman dalam memimpin tim dan membangun solusi digital yang memberikan dampak nyata terhadap perusahaan.",
      cvFile: "/CV-Dava-ID.pdf",
    },
    coreStacks: [
      { name: "PHP (Laravel/CI3)", percentage: 95 },
      { name: "JavaScript (React/Node)", percentage: 95 },
      { name: "Database (MySQL/Postgre)", percentage: 90 },
      { name: "Mobile (React Native)", percentage: 80 },
    ],
    otherSkills: [
      "Express.js",
      "REST API",
      "Git",
      "Tailwind CSS",
      "Bootstrap",
      "HTML/CSS",
    ],
    softSkills: [
      "Kepemimpinan Tim",
      "Pemecahan Masalah",
      "Manajemen Waktu",
      "Berpikir Kritis",
    ],
    projects: [
      {
        id: 1,
        title: "CRM Web",
        desc: "Sistem sentral untuk manajemen data pelanggan dan transaksi oleh Customer Service, dilengkapi modul pengolahan data pengiriman melalui integrasi API kurir, serta sinkronisasi dengan Web Order untuk manajemen leads yang terautomasi.",
        tech: "CI 3 | REST API | Webhook",
        thumbnail: "/projects/siciva.png",
        liveUrl: "",
        sourceUrl: "",
      },
      {
        id: 2,
        title: "Marketplace Data Sync",
        desc: "Aplikasi sentral pengolah data dari multi-platform e-commerce (Tokopedia, TikTok, Shopee, Lazada).",
        tech: "Laravel | REST API",
        thumbnail: "/projects/marketplace.png",
        liveUrl: "",
        sourceUrl: "",
      },
      {
        id: 3,
        title: "Omnichannel Web",
        desc: "Sistem Komunikasi Terintegrasi yang terhubung dengan API Meta (WA Business resmi) via Vonage untuk jangkauan pelanggan.",
        tech: "API Integration | Laravel | Node.js | Socket.io",
        thumbnail: "/projects/natcare.png",
        liveUrl: "",
        sourceUrl: "",
      },
      {
        id: 4,
        title: "Navilate (Affiliate System)",
        desc: "Sistem manajemen affiliator end-to-end berbasis web untuk memantau siklus transaksi dan perhitungan komisi secara otomatis.",
        tech: "Express.js | React.js",
        thumbnail: "/projects/navilate.png",
        liveUrl: "",
        sourceUrl: "",
      },
      {
        id: 5,
        title: "Evaluna (Performance Review Sys & Asset Mgt)",
        desc: "Sistem penilaian kinerja karyawan (OKR) komprehensif terintegrasi dengan modul manajemen aset. Dilengkapi aplikasi mobile untuk kemudahan akses tim.",
        tech: "Express.js | React | React Native",
        thumbnail: "/projects/evaluna.png",
        liveUrl: "",
        sourceUrl: "",
      },
      {
        id: 6,
        title: "E-Ticketing Kapal",
        desc: "Sistem e-ticketing kapal dengan integrasi Midtrans untuk proses pembayaran digital dan validasi transaksi. Status: Ongoing.",
        tech: "Laravel | Midtrans API | React.js",
        thumbnail: "/projects/eticketing-kapal.png",
        liveUrl: "",
        sourceUrl: "",
      },
      {
        id: 7,
        title: "LMS Internal Perusahaan",
        desc: "Learning Management System untuk kebutuhan internal perusahaan, mencakup manajemen materi, progress pembelajaran, dan evaluasi. Status: Ongoing.",
        tech: "Laravel | React.js | REST API",
        thumbnail: "/projects/lms-internal.png",
        liveUrl: "",
        sourceUrl: "",
      },
      {
        id: 8,
        title: "Equall (Split Bill Calculator)",
        desc: "Kalkulator split bill untuk publik tanpa perlu login, tanpa perlu download aplikasi, dan bisa langsung dipakai lewat web. Status: Live.",
        tech: "React.js | Vite | Web App",
        thumbnail: "/projects/equall.png",
        liveUrl: "https://equall.itsdep.space/",
        sourceUrl: "",
      },
    ],
    experience: [
      {
        id: 1,
        title: "IT Leader",
        company: "PT Naturalva Herba Indonesia",
        date: "Des 2025 - Sekarang",
      },
      {
        id: 2,
        title: "Full Stack Developer",
        company: "PT Naturalva Herba Indonesia",
        date: "Jan 2025 - Nob 2025",
      },
      {
        id: 3,
        title: "Web Developer",
        company: "PT Naturalva Herba Indonesia",
        date: "Feb 2024 - Des 2024",
      },
      {
        id: 4,
        title: "Intern Web Developer",
        company: "PT Naturalva Herba Indonesia",
        date: "November 2023 - Feb 2024",
      },
    ],
  },

  en: {
    seo: {
      title: "Dava Dwi | IT Leader & Full Stack Developer",
      description:
        "Building web and mobile systems including Performance Review Sys, CRM, affiliate management, and e-commerce data synchronization. Experienced in PHP, Laravel, CodeIgniter, React, Node.js, and API integration.",
      keywords:
        "Muhamad Dava, Dava Dwi, IT Leader, Full Stack Developer, Web Developer Bekasi, Software Engineer Indonesia, PHP, Laravel, CodeIgniter, JavaScript, React JS, Node JS, React Native, REST API, Performance Review Sys System, CRM, API Integration, Webhook",
    },
    nav: {
      viewExp: "View Experience",
      viewProj: "Highlighted Projects",
      featuredProj: "Featured Projects",
      workExp: "Work Experience",
      location: "Location",
      experience: "Experience",
      coreStacks: "Core Tech Stack",
      otherSkills: "Other Tools & Skills",
      softSkills: "Soft Skills",
      visitProject: "Open Project",
      viewSource: "View Source",
      screenshotOnly: "Screenshot Only",
      downloadCV: "Download CV (PDF)",
    },
    personal: {
      name: "Dava Dwi",
      fullName: "Muhamad Dava Dwi Saputra",
      role: "IT Leader | Full Stack Developer",
      email: "davadwi123@gmail.com",
      linkedin: "linkedin.com/in/muhamaddava",
      whatsapp: "6285183323882",
      github: "github.com/davadwis",
      city: "Bekasi Regency, Indonesia",
      yearsExp: "2+ Years",
      headline: "Crafting solid systems for growing businesses.",
      summary:
        "I am an IT Leader & Full Stack Developer focusing on backend architecture, API integrations, and operational efficiency. Experienced in leading teams and building digital solutions that deliver real impact to the company.",
      cvFile: "/CV-Dava-EN.pdf",
    },
    coreStacks: [
      { name: "PHP (Laravel/CI3)", percentage: 95 },
      { name: "JavaScript (React/Node)", percentage: 95 },
      { name: "Database (MySQL/Postgre)", percentage: 90 },
      { name: "Mobile (React Native)", percentage: 80 },
    ],
    otherSkills: [
      "Express.js",
      "REST API",
      "Git",
      "Tailwind CSS",
      "Bootstrap",
      "HTML/CSS",
    ],
    softSkills: [
      "Team Leadership",
      "Problem Solving",
      "Time Management",
      "Critical Thinking",
    ],
    projects: [
      {
        id: 1,
        title: "CRM Web",
        desc: "A centralized system for customer data and transaction management by Customer Service, featuring shipping processing modules via API integration and synchronization with Web Order for automated leads management.",
        tech: "CI 3 | REST API | Webhook",
        thumbnail: "/projects/siciva.png",
        liveUrl: "",
        sourceUrl: "",
      },
      {
        id: 2,
        title: "Marketplace Data Sync",
        desc: "Centralized application processing data from multiple e-commerce platforms (Tokopedia, TikTok, Shopee, Lazada).",
        tech: "Laravel | REST API",
        thumbnail: "/projects/marketplace.png",
        liveUrl: "",
        sourceUrl: "",
      },
      {
        id: 3,
        title: "Omnichannel Web",
        desc: "Integrated Communication System connected to the Meta API (official WA Business) via Vonage for scalable customer reach.",
        tech: "API Integration | Laravel | Node.js | Socket.io",
        thumbnail: "/projects/natcare.png",
        liveUrl: "",
        sourceUrl: "",
      },
      {
        id: 4,
        title: "Navilate (Affiliate System)",
        desc: "End-to-end web-based affiliate management system to monitor transaction cycles and automate commission calculations.",
        tech: "Express.js | React.js",
        thumbnail: "/projects/navilate.png",
        liveUrl: "",
        sourceUrl: "",
      },
      {
        id: 5,
        title: "Evaluna (Performance Review Sys & Asset Mgt)",
        desc: "Comprehensive employee performance appraisal system (OKRs) integrated with an asset management module. Includes a companion mobile app for team accessibility.",
        tech: "Express.js | React | React Native",
        thumbnail: "/projects/evaluna.png",
        liveUrl: "",
        sourceUrl: "",
      },
      {
        id: 6,
        title: "Ship E-Ticketing System",
        desc: "A ship e-ticketing system integrated with Midtrans for digital payment processing and transaction validation. Status: Ongoing.",
        tech: "Laravel | Midtrans API | React.js",
        thumbnail: "/projects/eticketing-kapal.png",
        liveUrl: "",
        sourceUrl: "",
      },
      {
        id: 7,
        title: "Internal Company LMS",
        desc: "A Learning Management System for internal company use, covering course material management, learning progress tracking, and evaluation modules. Status: Ongoing.",
        tech: "Laravel | React.js | REST API",
        thumbnail: "/projects/lms-internal.png",
        liveUrl: "",
        sourceUrl: "",
      },
      {
        id: 8,
        title: "Equall (Split Bill Calculator)",
        desc: "A public split bill calculator that can be used instantly without login and without downloading any app. Status: Live.",
        tech: "React.js | Vite | Web App",
        thumbnail: "/projects/equall.png",
        liveUrl: "https://equall.itsdep.space/",
        sourceUrl: "",
      },
    ],
    experience: [
      {
        id: 1,
        title: "IT Leader",
        company: "PT Naturalva Herba Indonesia",
        date: "Des 2025 - Sekarang",
      },
      {
        id: 2,
        title: "Full Stack Developer",
        company: "PT Naturalva Herba Indonesia",
        date: "Jan 2025 - Nob 2025",
      },
      {
        id: 3,
        title: "Web Developer",
        company: "PT Naturalva Herba Indonesia",
        date: "Feb 2024 - Des 2024",
      },
      {
        id: 4,
        title: "Intern Web Developer",
        company: "PT Naturalva Herba Indonesia",
        date: "November 2023 - Feb 2024",
      },
    ],
  },
};
